package main.websocket;

public enum  MessageType {
    ADMIN_JOINED, USER_JOINED, USER_LEFT, ACTIVE_USERS,
    ADMIN_SUCCESSFULLY_JOINED, GUEST_SUCCESSFULLY_JOINED,
    SCORE_1, SCORE_2, SCORE_3,
    MISS_1, MISS_2, MISS_3,
    REBOUND,
    ASSSIST,
    TURNOUVER,


}
