package main.websocket;

public enum  MessageType {
    ADMIN_JOINED, USER_JOINED, USER_LEFT, ACTIVE_USERS,
    SEND_START_GAME, SEND_END_GAME, RECEIVE_START_GAME, RECEIVE_END_GAME,
    ADMIN_SUCCESSFULLY_JOINED, GUEST_SUCCESSFULLY_JOINED, ADMIN_SUCCESSFULL_REFRESH,
    SEND_SCORE_1, SEND_SCORE_2, SEND_SCORE_3, RECEIVE_SCORE_1, RECEIVE_SCORE_2, RECEIVE_SCORE_3,
    SEND_MISS_1, SEND_MISS_2, SEND_MISS_3, RECEIVE_MISS_1, RECEIVE_MISS_2, RECEIVE_MISS_3,
    SEND_OFF_REBOUND, SEND_DEF_REBOUND,
    SEND_BLOCKED_SHOT, SEND_ASSIST, SEND_STEAL, SEND_TURNOVER,
    SEND_FOUL, SEND_FOUL_DRAWN,
    SEND_CHANGE_QUATER, RECEIVE_CHANGE_QUATER,
    SEND_TIMEOUT, SEND_SUBSTITUTION, RECEIVE_SUBSTITUTION,
    RECEIVE_STATS_UPDATE,
    SEND_PLAYERS_TIME, RECEIVE_PLAYERS_TIME

}
